version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ../wp/cms:/var/www/html

  db:
    image: mysql:5.7
    container_name: DBCONTAINER
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

volumes:
  wordpress:
  db: